### ISSUE TITLE
Update terminal line on homepage

### ISSUE THREAD

**Issue by domdomegg** [CLSB-Programming/clsb-programming.github.io#10]
- [ ] Change colours to colours used in Linux terminal that look nicer, namely `#8AE234` and `#729FCF`
- [x] Remove div that doesn't do anything
- [ ] Remove space between `~` and `$` and add `:`
- [ ] Change blue span tag to only go around `~`, as `$` should be white

Here's a picture of the terminal for reference:
![screenshot from 2016-12-05 22-34-06](https://cloud.githubusercontent.com/assets/4953590/20905825/66313b42-bb3d-11e6-96d7-34ebf7b4a524.png)

Maybe even later we could introduce a text field and some javascript and see if we can have some cheat codes you could enter into it as [easter eggs](https://en.wikipedia.org/wiki/Easter_egg_(media)#Software).

**Comment by jcxldn** [comment]
http://d2r5da613aq50s.cloudfront.net/wp-content/uploads/488025.image0.jpg

![alt text](http://d2r5da613aq50s.cloudfront.net/wp-content/uploads/488025.image0.jpg "Title")

Anything to say about the RPi terminal then?

**Comment by domdomegg** [comment]
ah k - that's what you were modelling it on.

Issue closed

**Comment by jcxldn** [comment]
Lol
