### ISSUE TITLE
Fix title on mobile

### ISSUE THREAD

**Issue by domdomegg** [CLSB-Programming/clsb-programming.github.io#35]
e.g. on very thin widths the title gets cut off
![screenshot from 2017-01-19 21-16-20](https://cloud.githubusercontent.com/assets/4953590/22125676/8ac7053c-de8c-11e6-8774-e7efdcf024c4.png)

Hint: You could do this with [media queries](http://www.w3schools.com/css/css_rwd_mediaqueries.asp), by setting the `display` attribute to `none` on certain parts of the title, as well as decreasing `padding` and `font-size`.

**Comment by domdomegg** [comment]
[Mozilla](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries) is also a great resource, although often at a higher standard and explained in a more complex way. Have a look around and try to learn for yourself though ;)

Any questions please ask me

**Comment by jcxldn** [comment]
Ok. Going to try with this page - http://www.inmotionhosting.com/support/website/redirects/mobile-redirect

**Comment by domdomegg** [comment]
@Prouser123 I didn't mean to redirect mobile users to another site, as that will create a load more work maintaining the site. [Responsive design](http://www.w3schools.com/css/css_rwd_intro.asp) is very often used now and means you only have to write the content once. Have a look at media queries to create certain CSS rules for people with small screen sizes.

There's also a great guide by [Google developers](https://developers.google.com/web/fundamentals/design-and-ui/responsive/) on responsive design

**Comment by jcxldn** [comment]
Coudn't we just iframe in the content from that page?
