### ISSUE TITLE
Make people use 'suitable' commit names.

### ISSUE THREAD

**Issue by jcxldn** [CLSB-Programming/clsb-programming.github.io#8]
A good example for someone that should do this is Thomas. I mean, really, is ;aetbhbhbhbhbhbhbhbhbhbhbhbhbhbhbhbhjksd a good commit name? No it's not.

**Comment by domdomegg** [comment]
I'll bring it up in the next session and tell people not to if they submit a pull request with inappropriate commit names

**Comment by jcxldn** [comment]
Ok. Do it on Monday.

**Comment by domdomegg** [comment]
Done
