### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by jcxldn** [CLSB-Programming/clsb-programming.github.io#80]
It's about time we did some releases. Maybe do #78  & #79 and make sure the whole site is working properly and do a stable release? Because, you know, it's not all working as of now.

**Comment by domdomegg** [comment]
What isn't working?

Also don't really see the point in managing releases for this - slows development of people's pages + if one page breaks doesn't affect others so it's not *too* bad having parts that are broken (compared to an android app where a single line missing a semicolon will cause a fatal crash every time)

**Comment by jcxldn** [comment]
Point taken
